// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKCBrDlvq0lsGyEYWbnuS1iCxT_ePruQY',
    appId: '1:321435976541:web:3a9a10bb619950a5969eb4',
    messagingSenderId: '321435976541',
    projectId: 'inventory-management-flutter',
    authDomain: 'inventory-management-flutter.firebaseapp.com',
    storageBucket: 'inventory-management-flutter.firebasestorage.app',
    measurementId: 'G-V5BE5D3N48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUil11iAxKlywKk8T4EZ6Zmx3oPaI95Ek',
    appId: '1:321435976541:android:3d81b94ae59a5d31969eb4',
    messagingSenderId: '321435976541',
    projectId: 'inventory-management-flutter',
    storageBucket: 'inventory-management-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxo2MUThNbZl1n3eNd-MZjy0z3DYERNP4',
    appId: '1:321435976541:ios:16707d38049aeabf969eb4',
    messagingSenderId: '321435976541',
    projectId: 'inventory-management-flutter',
    storageBucket: 'inventory-management-flutter.firebasestorage.app',
    iosBundleId: 'com.example.wandermate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxo2MUThNbZl1n3eNd-MZjy0z3DYERNP4',
    appId: '1:321435976541:ios:16707d38049aeabf969eb4',
    messagingSenderId: '321435976541',
    projectId: 'inventory-management-flutter',
    storageBucket: 'inventory-management-flutter.firebasestorage.app',
    iosBundleId: 'com.example.wandermate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKCBrDlvq0lsGyEYWbnuS1iCxT_ePruQY',
    appId: '1:321435976541:web:c032760072c5f0c4969eb4',
    messagingSenderId: '321435976541',
    projectId: 'inventory-management-flutter',
    authDomain: 'inventory-management-flutter.firebaseapp.com',
    storageBucket: 'inventory-management-flutter.firebasestorage.app',
    measurementId: 'G-1EBGWS9T3P',
  );

}